// قائمة بجميع دول العالم مرتبة أبجدياً باللغة العربية
export const countries = [
  { value: "EG", label: "مصر" },
  { value: "SA", label: "السعودية" },
  { value: "AE", label: "الإمارات العربية المتحدة" },
  { value: "JO", label: "الأردن" },
  { value: "LB", label: "لبنان" },
  { value: "SY", label: "سوريا" },
  { value: "IQ", label: "العراق" },
  { value: "KW", label: "الكويت" },
  { value: "QA", label: "قطر" },
  { value: "BH", label: "البحرين" },
  { value: "OM", label: "عمان" },
  { value: "YE", label: "اليمن" },
  { value: "PS", label: "فلسطين" },
  { value: "LY", label: "ليبيا" },
  { value: "TN", label: "تونس" },
  { value: "DZ", label: "الجزائر" },
  { value: "MA", label: "المغرب" },
  { value: "SD", label: "السودان" },
  { value: "SO", label: "الصومال" },
  { value: "DJ", label: "جيبوتي" },
  { value: "KM", label: "جزر القمر" },
  { value: "MR", label: "موريتانيا" },
  { value: "AF", label: "أفغانستان" },
  { value: "AL", label: "ألبانيا" },
  { value: "AD", label: "أندورا" },
  { value: "AO", label: "أنغولا" },
  { value: "AG", label: "أنتيغوا وبربودا" },
  { value: "AR", label: "الأرجنتين" },
  { value: "AM", label: "أرمينيا" },
  { value: "AU", label: "أستراليا" },
  { value: "AT", label: "النمسا" },
  { value: "AZ", label: "أذربيجان" },
  { value: "BS", label: "باهاماس" },
  { value: "BD", label: "بنغلاديش" },
  { value: "BB", label: "بربادوس" },
  { value: "BY", label: "بيلاروسيا" },
  { value: "BE", label: "بلجيكا" },
  { value: "BZ", label: "بليز" },
  { value: "BJ", label: "بنين" },
  { value: "BT", label: "بوتان" },
  { value: "BO", label: "بوليفيا" },
  { value: "BA", label: "البوسنة والهرسك" },
  { value: "BW", label: "بوتسوانا" },
  { value: "BR", label: "البرازيل" },
  { value: "BN", label: "بروناي" },
  { value: "BG", label: "بلغاريا" },
  { value: "BF", label: "بوركينا فاسو" },
  { value: "BI", label: "بوروندي" },
  { value: "CV", label: "الرأس الأخضر" },
  { value: "KH", label: "كمبوديا" },
  { value: "CM", label: "الكاميرون" },
  { value: "CA", label: "كندا" },
  { value: "CF", label: "جمهورية أفريقيا الوسطى" },
  { value: "TD", label: "تشاد" },
  { value: "CL", label: "تشيلي" },
  { value: "CN", label: "الصين" },
  { value: "CO", label: "كولومبيا" },
  { value: "CR", label: "كوستاريكا" },
  { value: "CI", label: "ساحل العاج" },
  { value: "HR", label: "كرواتيا" },
  { value: "CU", label: "كوبا" },
  { value: "CY", label: "قبرص" },
  { value: "CZ", label: "التشيك" },
  { value: "CD", label: "جمهورية الكونغو الديمقراطية" },
  { value: "DK", label: "الدنمارك" },
  { value: "DM", label: "دومينيكا" },
  { value: "DO", label: "جمهورية الدومينيكان" },
  { value: "EC", label: "الإكوادور" },
  { value: "SV", label: "السلفادور" },
  { value: "GQ", label: "غينيا الاستوائية" },
  { value: "ER", label: "إريتريا" },
  { value: "EE", label: "إستونيا" },
  { value: "SZ", label: "إسواتيني" },
  { value: "ET", label: "إثيوبيا" },
  { value: "FJ", label: "فيجي" },
  { value: "FI", label: "فنلندا" },
  { value: "FR", label: "فرنسا" },
  { value: "GA", label: "الغابون" },
  { value: "GM", label: "غامبيا" },
  { value: "GE", label: "جورجيا" },
  { value: "DE", label: "ألمانيا" },
  { value: "GH", label: "غانا" },
  { value: "GR", label: "اليونان" },
  { value: "GD", label: "غرينادا" },
  { value: "GT", label: "غواتيمالا" },
  { value: "GN", label: "غينيا" },
  { value: "GW", label: "غينيا بيساو" },
  { value: "GY", label: "غيانا" },
  { value: "HT", label: "هايتي" },
  { value: "HN", label: "هندوراس" },
  { value: "HU", label: "المجر" },
  { value: "IS", label: "آيسلندا" },
  { value: "IN", label: "الهند" },
  { value: "ID", label: "إندونيسيا" },
  { value: "IR", label: "إيران" },
  { value: "IE", label: "أيرلندا" },
  { value: "IL", label: "إسرائيل" },
  { value: "IT", label: "إيطاليا" },
  { value: "JM", label: "جامايكا" },
  { value: "JP", label: "اليابان" },
  { value: "KZ", label: "كازاخستان" },
  { value: "KE", label: "كينيا" },
  { value: "KI", label: "كيريباتي" },
  { value: "KP", label: "كوريا الشمالية" },
  { value: "KR", label: "كوريا الجنوبية" },
  { value: "XK", label: "كوسوفو" },
  { value: "KG", label: "قيرغيزستان" },
  { value: "LA", label: "لاوس" },
  { value: "LV", label: "لاتفيا" },
  { value: "LS", label: "ليسوتو" },
  { value: "LR", label: "ليبيريا" },
  { value: "LI", label: "ليختنشتاين" },
  { value: "LT", label: "ليتوانيا" },
  { value: "LU", label: "لوكسمبورغ" },
  { value: "MG", label: "مدغشقر" },
  { value: "MW", label: "مالاوي" },
  { value: "MY", label: "ماليزيا" },
  { value: "MV", label: "المالديف" },
  { value: "ML", label: "مالي" },
  { value: "MT", label: "مالطا" },
  { value: "MH", label: "جزر مارشال" },
  { value: "MX", label: "المكسيك" },
  { value: "FM", label: "ميكرونيزيا" },
  { value: "MD", label: "مولدوفا" },
  { value: "MC", label: "موناكو" },
  { value: "MN", label: "منغوليا" },
  { value: "ME", label: "الجبل الأسود" },
  { value: "MZ", label: "موزمبيق" },
  { value: "MM", label: "ميانمار" },
  { value: "NA", label: "ناميبيا" },
  { value: "NR", label: "ناورو" },
  { value: "NP", label: "نيبال" },
  { value: "NL", label: "هولندا" },
  { value: "NZ", label: "نيوزيلندا" },
  { value: "NI", label: "نيكاراغوا" },
  { value: "NE", label: "النيجر" },
  { value: "NG", label: "نيجيريا" },
  { value: "MK", label: "مقدونيا الشمالية" },
  { value: "NO", label: "النرويج" },
  { value: "PK", label: "باكستان" },
  { value: "PW", label: "بالاو" },
  { value: "PA", label: "بنما" },
  { value: "PG", label: "بابوا غينيا الجديدة" },
  { value: "PY", label: "باراغواي" },
  { value: "PE", label: "بيرو" },
  { value: "PH", label: "الفلبين" },
  { value: "PL", label: "بولندا" },
  { value: "PT", label: "البرتغال" },
  { value: "RO", label: "رومانيا" },
  { value: "RU", label: "روسيا" },
  { value: "RW", label: "رواندا" },
  { value: "KN", label: "سانت كيتس ونيفيس" },
  { value: "LC", label: "سانت لوسيا" },
  { value: "VC", label: "سانت فنسنت والغرينادين" },
  { value: "WS", label: "ساموا" },
  { value: "SM", label: "سان مارينو" },
  { value: "ST", label: "ساو تومي وبرينسيبي" },
  { value: "SN", label: "السنغال" },
  { value: "RS", label: "صربيا" },
  { value: "SC", label: "سيشيل" },
  { value: "SL", label: "سيراليون" },
  { value: "SG", label: "سنغافورة" },
  { value: "SK", label: "سلوفاكيا" },
  { value: "SI", label: "سلوفينيا" },
  { value: "SB", label: "جزر سليمان" },
  { value: "ZA", label: "جنوب أفريقيا" },
  { value: "SS", label: "جنوب السودان" },
  { value: "ES", label: "إسبانيا" },
  { value: "LK", label: "سريلانكا" },
  { value: "SR", label: "سورينام" },
  { value: "SE", label: "السويد" },
  { value: "CH", label: "سويسرا" },
  { value: "TJ", label: "طاجيكستان" },
  { value: "TZ", label: "تنزانيا" },
  { value: "TH", label: "تايلاند" },
  { value: "TL", label: "تيمور الشرقية" },
  { value: "TG", label: "توغو" },
  { value: "TO", label: "تونغا" },
  { value: "TT", label: "ترينيداد وتوباغو" },
  { value: "TR", label: "تركيا" },
  { value: "TM", label: "تركمانستان" },
  { value: "TV", label: "توفالو" },
  { value: "UG", label: "أوغندا" },
  { value: "UA", label: "أوكرانيا" },
  { value: "GB", label: "المملكة المتحدة" },
  { value: "US", label: "الولايات المتحدة" },
  { value: "UY", label: "أوروغواي" },
  { value: "UZ", label: "أوزبكستان" },
  { value: "VU", label: "فانواتو" },
  { value: "VA", label: "الفاتيكان" },
  { value: "VE", label: "فنزويلا" },
  { value: "VN", label: "فيتنام" },
  { value: "ZM", label: "زامبيا" },
  { value: "ZW", label: "زيمبابوي" }
];
